export const models = [
  { id: "gpt-4", name: "GPT-4" },
  { id: "gpt-4o-mini", name: "GPT-4o Mini" },
  { id: "gpt-4o", name: "GPT-4o" },
  { id: "o1", name: "o1" },
  { id: "o1-mini", name: "o1 Mini" },
  { id: "o3", name: "o3" },
  { id: "o3-mini", name: "o3 Mini" },
  { id: "o4-mini", name: "o4 Mini" },
  { id: "gpt-4.5-preview", name: "GPT-4.5 Preview" },
  { id: "gpt-4.1", name: "GPT-4.1" },
  { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
  { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
  { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet" },
  { id: "claude-3-5-haiku", name: "Claude 3.5 Haiku" },
  { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet" },
  { id: "claude-sonnet-4", name: "Claude Sonnet 4" },
  { id: "claude-opus-4", name: "Claude Opus 4" },
  { id: "grok-3", name: "Grok 3" },
  { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
  { id: "deepseek-r1", name: "DeepSeek R1" },
  { id: "deepseek-v3", name: "DeepSeek V3" },
];

export const searchModel = "sonar-pro";